%endoflist

    %externalintegerfn %spec fault count
    %externalroutine %spec another fault
    %externalroutine %spec flush buffer
    %externalpredicate %spec near buffer limit
    %externalroutine %spec add char( %byteinteger ch )
    %externalroutine %spec add long( %integer m )
    %externalroutine %spec add string( %string(255) s )

    { This loads the iCode instruction and the 2-byte parameter }
    %externalroutine %spec add operation(%integer code, param)
    %externalroutine %spec Append Tag(%integer Tag)
    %externalroutine %spec octal(%integer n)
    %externalroutine %spec hexadecimal(%integer n)

%list
%endoffile
