%endoflist
%constinteger Source         = 1,  Predef In     = 2

%constinteger Icode In       = 1,  Icode Out     = 1,
              Icode In2      = 2,
              Report         = 0,
              Objectives Out = 1,  Objectives In = 1,  PrimObj In = 3,
              Directives Out = 2,  Directives In = 2,  PrimDir In = 4,
              Object Out     = 1,  Decode Out    = 3,
              Listing        = 7
%list
%endoffile
